#!/usr/bin/env bash

python3 -c "
import socket
s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
s.bind(('localhost', 98))
s.listen(1)
while True:
	conn, addr = s.accept()
	data = conn.recv(1024)
	if data:
		print(data.decode('utf-8').strip())
	conn.close()
"
